
class Registration:
    NEUTRAL = None
    STARTED_REGISTRATION = 0
    REGISTERING_NAME = 1
    REGISTERING_PHONE = 2

class CreatingPost:
    NEUTRAL = None
    CREATING_POST = 3
    EDITING_POST = 4
    EDITING_POST_PRICE = 5
    EDITING_POST_DESCRIPTION = 6
    EDITING_POST_QUANTITY = 7
