class Delivery:
    NEUTRAL = None
    EDITING_PHONE = None
    EDITING_ADDRESS = None
class Registration:
    NEUTRAL = None
    STARTED_REGISTRATION = 0
    REGISTERING_NAME = 1
    REGISTERING_PHONE = 2

class CreatingPost:
    NEUTRAL = None
    CREATING_POST = 3
    EDITING_POST = 4
    EDITING_POST_PRICE = 5
    EDITING_POST_DESCRIPTION = 6
    EDITING_POST_QUANTITY = 7

class AuditPosts:
    NEUTRAL = None
    EDITING_POST_AUDIT = 8
    EDITING_POST_PRICE_AUDIT = 9
    EDITING_POST_DESCRIPTION_AUDIT = 10
    EDITING_POST_QUANTITY_AUDIT = 11
